/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;

/**
 *
 * @author Nikolaj
 */
public class EditArrangement extends javax.swing.JPanel {

    /**
     * Creates new form EditArrangement
     */
    public EditArrangement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        ArrangemenOptions = new javax.swing.ButtonGroup();
        editTitleLabel = new javax.swing.JLabel();
        customerIDfield = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        arrangementList = new javax.swing.JList<>();
        moveArrangementButton = new javax.swing.JRadioButton();
        cancelArrangementButton = new javax.swing.JRadioButton();
        newFromDateLabel = new javax.swing.JLabel();
        newToDateLabel = new javax.swing.JLabel();
        confirmationLabel = new javax.swing.JLabel();
        confirmationCheckBox = new javax.swing.JCheckBox();
        doneButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        fromDatePicker = new org.jdesktop.swingx.JXDatePicker();
        toDatePicker = new org.jdesktop.swingx.JXDatePicker();

        setPreferredSize(new java.awt.Dimension(760, 600));

        editTitleLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        editTitleLabel.setText("Edit Arrangement(s)");

        customerIDfield.setText("CustomerID");
        customerIDfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(FocusEvent evt) {
                customerIDfieldFocusGained(evt);
            }
        });

        arrangementList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(arrangementList);

        ArrangemenOptions.add(moveArrangementButton);
        moveArrangementButton.setText("Move Arrangement");

        ArrangemenOptions.add(cancelArrangementButton);
        cancelArrangementButton.setText("Cancel Arrangement");

        newFromDateLabel.setText("New Date From:");

        newToDateLabel.setText("New Date To:");

        confirmationLabel.setText("Confirm Change");

        doneButton.setText("Done");

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Arrangement Description");
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(customerIDfield, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(editTitleLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(newFromDateLabel, javax.swing.GroupLayout.Alignment.LEADING))
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(moveArrangementButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(confirmationLabel)
                                                                                        .addComponent(doneButton))
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                .addComponent(confirmationCheckBox))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(fromDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(34, 34, 34)
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(newToDateLabel)
                                                                                        .addComponent(toDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addComponent(cancelArrangementButton))))
                                                                .addGap(0, 0, Short.MAX_VALUE)))
                                                .addGap(132, 132, 132))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {fromDatePicker, toDatePicker});

        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(editTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(customerIDfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane2)
                                        .addComponent(jScrollPane1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(moveArrangementButton)
                                        .addComponent(cancelArrangementButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(newFromDateLabel)
                                        .addComponent(newToDateLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(fromDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(toDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(confirmationLabel)
                                        .addComponent(confirmationCheckBox))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(doneButton)
                                .addContainerGap(139, Short.MAX_VALUE))
        );
    }// </editor-fold>

    private void customerIDfieldFocusGained(FocusEvent evt) {
        // TODO add your handling code here:
        customerIDfield.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                customerIDfield.setText("");
            }

            @Override
            public void focusLost(FocusEvent e) {

            }
        });
    }


    // Variables declaration - do not modify
    private javax.swing.ButtonGroup ArrangemenOptions;
    private javax.swing.JList<String> arrangementList;
    private javax.swing.JRadioButton cancelArrangementButton;
    private javax.swing.JCheckBox confirmationCheckBox;
    private javax.swing.JLabel confirmationLabel;
    private javax.swing.JTextField customerIDfield;
    private javax.swing.JButton doneButton;
    private javax.swing.JLabel editTitleLabel;
    private org.jdesktop.swingx.JXDatePicker fromDatePicker;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JRadioButton moveArrangementButton;
    private javax.swing.JLabel newFromDateLabel;
    private javax.swing.JLabel newToDateLabel;
    private org.jdesktop.swingx.JXDatePicker toDatePicker;
    // End of variables declaration
}
