package GUI;/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import Domain.Controller;

import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 * @author Kasper
 */
public class ReservationOverview extends javax.swing.JPanel {
    Controller controller;

    /**
     * Creates new form ReservationOverview
     */
    public ReservationOverview(Controller controller) {
        this.controller = controller;
        initComponents();
        try {
            getDataToOverview();
            deleteButtonActionPerformed();
        } catch (SQLException e) {
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        // Initializing the components
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        OverviewTable = new javax.swing.JTable();
        deleteButton = new javax.swing.JButton();
        headlineLabel = new javax.swing.JLabel();

        // Setting height of rows
        OverviewTable.setRowHeight(50);
        // Creating the JTable
        OverviewTable.setModel(new DefaultTableModel(
                new Object[][]{
                },
                new String[]{
                        "BookingID", "CustomerID", "RoomID", "User ID", "DateFrom", "DateTo"
                }
        ));
        model = (DefaultTableModel) OverviewTable.getModel();
        jScrollPane1.setViewportView(OverviewTable);
        deleteButton.setText("Delete");
        jButton1.setText("jButton1");
        headlineLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        headlineLabel.setText("Reservation overview");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(12, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(headlineLabel)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(deleteButton)
                                                .addContainerGap(35, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(41, Short.MAX_VALUE)
                                .addComponent(headlineLabel)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(35, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(65, 65, 65)
                                                .addComponent(deleteButton)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>

    private void deleteButtonActionPerformed() throws SQLException {
        deleteButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int id = Integer.parseInt(OverviewTable.getValueAt(OverviewTable.getSelectedRow(), 0).toString());
                try {
                    controller.deleteReservation(id);
                } catch (SQLException e1) {
                    e1.printStackTrace();
                }
                model.removeRow(OverviewTable.getSelectedRow());
            }
        });
    }

    private void getDataToOverview() throws SQLException {
        ResultSet rs = controller.getDataToOverview();
        insertDataToOverview(rs);
    }

    private void insertDataToOverview(ResultSet rs) {
        try {
            while (rs.next()) {
                model.addRow(new Object[]{(rs.getInt(1)), rs.getInt(2), rs.getInt(3), rs.getInt(4), rs.getDate(5), rs.getDate(6)});
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }


    // Variables declaration - do not modify
    private javax.swing.JTable OverviewTable;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel headlineLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private DefaultTableModel model;

    // End of variables declaration
}
