/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Nikolaj
 */
public class ViewAllArrangements extends javax.swing.JPanel {

    /**
     * Creates new form viewArrangements
     */
    public ViewAllArrangements() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        viewArrangementsLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        arrangementOverviewTable = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(760, 600));

        viewArrangementsLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        viewArrangementsLabel.setText("View Arrangements");

        arrangementOverviewTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null, null, null},
                        {null, null, null, null, null, null},
                        {null, null, null, null, null, null},
                        {null, null, null, null, null, null},
                        {null, null, null, null, null, null},
                        {null, null, null, null, null, null},
                        {null, null, null, null, null, null},
                        {null, null, null, null, null, null},
                        {null, null, null, null, null, null},
                        {null, null, null, null, null, null}
                },
                new String [] {
                        "ArrangementID", "CustomerID", "Arrangement Name", "Description", "Price", "Number of Guests"
                }
        ) {
            Class[] types = new Class [] {
                    Integer.class, Integer.class, String.class, String.class, Double.class, Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        arrangementOverviewTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(arrangementOverviewTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(225, 225, 225)
                                .addComponent(viewArrangementsLabel)
                                .addContainerGap(226, Short.MAX_VALUE))
                        .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(viewArrangementsLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(259, Short.MAX_VALUE))
        );
    }// </editor-fold>


    // Variables declaration - do not modify
    private javax.swing.JTable arrangementOverviewTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel viewArrangementsLabel;
    // End of variables declaration
}
